DROP TABLE ratings;
DROP TABLE posts;
DROP TABLE users;

CREATE TABLE users(
userid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(100) NOT NULL,
fname VARCHAR(25) NOT NULL,
lname VARCHAR(25),
passhash VARCHAR(255) NOT NULL,
admin BOOLEAN NOT NULL
);

CREATE TABLE posts(
postid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
userid INT NOT NULL,
title VARCHAR(50) NOT NULL,
description VARCHAR(200),
FOREIGN KEY (userid) REFERENCES users(userid)
);

CREATE TABLE ratings(
ratingid  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
userid  INT NOT NULL,
postid  INT NOT NULL,
title VARCHAR(50) NOT NULL,
description VARCHAR(200) ,
rating INT NOT NULL,
FOREIGN KEY (postid) REFERENCES posts(postid),
FOREIGN KEY (userid) REFERENCES users(userid)
);
